[VIDEO-1693] s3sink: added 'location' property support
blinemedical/amazon-s3-gst-plugin pull request #1
Opened 2021-06-16 13:31 UTC by btgoodwin

New property sets and gets via 'bucket' and 'key' existing
properties.

Signed-off-by: Thomas Goodwin thomas.goodwin@laerdal.com

Issue #6

Description of changes:

Per the thread at #7, I added a new string property, location to be the URI comprised of the bucket and key properties. Setting location also sets bucket and key, getting location assembles the URI using bucket and key. A unit test has been added to verify the new behavior.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-16 15:12 UTC, jawilson requested changes
Looks like you're missing the "In addition have the `s3sink` element implement the `GstUriHandler` interface."

Info about the interface is [here](https://gstreamer.freedesktop.org/documentation/gstreamer/gsturihandler.html?gi-language=c). A test calling [`gst_element_make_from_uri`](https://gstreamer.freedesktop.org/documentation/gstreamer/gstelement.html?gi-language=c#gst_element_make_from_uri) should be added.

2021-06-16 15:47 UTC, btgoodwin commented
I just misunderstood that commentary as somehow implementing a location property was all that was required to get the interface to opaquely "just work" the way the original thread discussed.

2021-06-16 16:45 UTC, jawilson commented
That _may_ be the case, but we should add a test to ensure it works as expected. I think you may just need to register a handler or something.

2021-06-16 16:59 UTC, btgoodwin commented
No - you're correct, to implement that specific interface we have to use a method [described here](https://gstreamer.freedesktop.org/documentation/plugin-development/advanced/interfaces.html?gi-language=c) which I think is going to mean we cannot use the convenience method to set this up ahead of implementing the two virtual functions.  Then the rest of the API should _Just Work_.

2021-06-17 19:19 UTC, btgoodwin commented
I used the `gst-plugins-bad/ext/curl/gstcurlhttpsrc.c` as my example for tacking on the GstURIHandler interface.  I'm _pretty sure_ this answers the mail.  The `gst_element_make_from_uri` returns our element properly in the newly-added test.

2021-06-17 19:24 UTC, btgoodwin commented
Output from `gst-inspect-1.0`:
```
Factory Details:
  Rank                     none (0)
  Long-name                S3 Sink
  Klass                    Sink/S3
  Description              Write stream to an Amazon S3 bucket
  Author                   Marcin Kolny <marcin.kolny at gmail.com>

Plugin Details:
  Name                     s3elements
  Description              Amazon S3 elements
  Filename                 /home/thomasgoodwin/Projects/VIDEO-1693/amazon-s3-gst-plugin/builddir/src/libgsts3elements.so
  Version                  0.1.0
  License                  LGPL
  Source module            amazon-s3-gst-plugin
  Binary package           GStreamer S3 package
  Origin URL               https://www.amazon.com

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBaseSink
                         +----GstS3Sink

Implemented Interfaces:
  GstURIHandler
  ...
```

2021-06-17 19:39 UTC, jawilson approved these changes

2021-06-17 19:39 UTC, merged